name: ci

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2

      - name: Install npm dependencies
        run: npm install

      - name: Install composer dependencies
        run: composer install

      - name: Active CI .env
        run: mv .env.ci .env

      - name: Run tests
        run: npm run test
